version: '8.0.23-1debian10'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=root
    restart: always
    environment:
      environment:
            MYSQL_ROOT_PASSWORD: 'root';
            MYSQL_DATABASE: 'capstone';
            MYSQL_USER: 'root';
            MYSQL_PASSWORD: 'root';

  adminer:
    image: mysql:latest
    restart: always
    ports:
      - 3310:3306